//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCTTECHNOLOGIES.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DCTDBEntities : DbContext
    {
        public DCTDBEntities()
            : base("name=DCTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QueriesTbl> QueriesTbls { get; set; }
        public virtual DbSet<RegisterTbl> RegisterTbls { get; set; }
        public virtual DbSet<ReviewsTbl> ReviewsTbls { get; set; }
    }
}
